In [2]:
x = 4
y = 5

In [3]:
z = x + y
print(z)

9


In [4]:
w = x * y
print(w)

20


In [5]:
k = x - y
print(k)

-1


In [6]:
x < 3
x > 3

True

In [7]:
t = "hello world"
print(t)

hello world


Vectors now (like coordinates)

In [8]:
import numpy as np

In [9]:
v = np.array((-1.0, 2.6, 3.5, 4.1, 5.0))
print(v)

[-1.   2.6  3.5  4.1  5. ]


In [10]:
v1 = np.array(("hello", "world"))
print(v1)

['hello' 'world']


In [11]:
v2 = np.array(("TRUE", "FALSE", "TRUE", "FALSE", "FALSE", "TRUE", "TRUE"))
print(v2)

['TRUE' 'FALSE' 'TRUE' 'FALSE' 'FALSE' 'TRUE' 'TRUE']


In [12]:
v3 = np.array(("T", "F", "T"))
print(v3)

['T' 'F' 'T']


In [13]:
print(v * 2)
print(1 / v)
print(sum(v))
print(np.mean(v))
print(np.var(v))
print(np.max(v))
print(np.min(v))
print(v.size)

[-2.   5.2  7.   8.2 10. ]
[-1.          0.38461538  0.28571429  0.24390244  0.2       ]
14.2
2.84
4.2984
5.0
-1.0
5


In [14]:
print(sorted(v))
print(sorted(v, reverse = True))
print(sorted(v, reverse = False))

[-1.0, 2.6, 3.5, 4.1, 5.0]
[5.0, 4.1, 3.5, 2.6, -1.0]
[-1.0, 2.6, 3.5, 4.1, 5.0]


In [16]:
y1 = 1
x1 = np.array((2, 4, 5))
print(y1)
print(x1)

1
[2 4 5]


In [17]:
print(x1.size)

3


In [18]:
x[x<3]

TypeError: 'int' object is not subscriptable

EXERCISE 1
Write a script that:
1. creates a vector with some of your friend's names;
2. calculates the length of this vector;
3. returns the first two friends from this vector;
4. returns the 2nd and 3rd friend names;
5. sorts your friends by names;
6. reverses direction of the above sort.

Matrices

In [19]:
A = np.matrix('2, 4, 3; 1, 5, 7; 1, 2, 4')
print(A)

[[2 4 3]
 [1 5 7]
 [1 2 4]]


In [29]:
print(A[0])

[[2 4 3]]


In [30]:
print(A[:,0])

[[2]
 [1]
 [1]]


In [32]:
print(A.T)
print(A.diagonal())

[[2 1 1]
 [4 5 2]
 [3 7 4]]
[[2 5 4]]


In [35]:
B = np.arange(1, 10).reshape(3, 3)
print(B)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [36]:
print(A + B)
print(A * B)
print(np.matmul(A, B))

[[ 3  6  6]
 [ 5 10 13]
 [ 8 10 13]]
[[39 48 57]
 [70 83 96]
 [37 44 51]]
[[39 48 57]
 [70 83 96]
 [37 44 51]]
