In [23]:
x = 4
y = 5

In [24]:
z = x + y
print(z)

9


In [25]:
w = x * y
print(w)

20


In [26]:
k = x - y
print(k)

-1


In [27]:
x < 3
x > 3

True

In [28]:
t = "hello world"
print(t)

hello world


Vectors now (like coordinates)

In [29]:
import numpy as np

In [30]:
v = np.array((-1.0, 2.6, 3.5, 4.1, 5.0))
print(v)

[-1.   2.6  3.5  4.1  5. ]


In [31]:
v1 = np.array(("hello", "world"))
print(v1)

['hello' 'world']


In [32]:
v2 = np.array(("TRUE", "FALSE", "TRUE", "FALSE", "FALSE", "TRUE", "TRUE"))
print(v2)

['TRUE' 'FALSE' 'TRUE' 'FALSE' 'FALSE' 'TRUE' 'TRUE']


In [33]:
v3 = np.array(("T", "F", "T"))
print(v3)

['T' 'F' 'T']


In [34]:
print(v * 2)
print(1 / v)
print(sum(v))
print(np.mean(v))
print(np.var(v))
print(np.max(v))
print(np.min(v))
print(v.size)

[-2.   5.2  7.   8.2 10. ]
[-1.          0.38461538  0.28571429  0.24390244  0.2       ]
14.2
2.84
4.2984
5.0
-1.0
5


In [35]:
print(sorted(v))
print(sorted(v, reverse = True))
print(sorted(v, reverse = False))

[-1.0, 2.6, 3.5, 4.1, 5.0]
[5.0, 4.1, 3.5, 2.6, -1.0]
[-1.0, 2.6, 3.5, 4.1, 5.0]


In [36]:
y1 = 1
x1 = np.array((2, 4, 5))
print(y1)
print(x1)

1
[2 4 5]


In [37]:
print(x1.size)

3


EXERCISE 1
Write a script that:
1. creates a vector with some of your friend's names;
2. calculates the length of this vector;
3. returns the first two friends from this vector;
4. returns the 2nd and 3rd friend names;
5. sorts your friends by names;
6. reverses direction of the above sort.

Matrices

In [38]:
A = np.matrix('2, 4, 3; 1, 5, 7; 1, 2, 4')
print(A)

[[2 4 3]
 [1 5 7]
 [1 2 4]]


In [39]:
print(A[0])

[[2 4 3]]


In [40]:
print(A[:,0])

[[2]
 [1]
 [1]]


In [41]:
print(A.T)
print(A.diagonal())

[[2 1 1]
 [4 5 2]
 [3 7 4]]
[[2 5 4]]


In [42]:
B = np.arange(1, 10).reshape(3, 3)
print(B)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [43]:
print(A + B)
print(A * B)
print(np.matmul(A, B))

[[ 3  6  6]
 [ 5 10 13]
 [ 8 10 13]]
[[39 48 57]
 [70 83 96]
 [37 44 51]]
[[39 48 57]
 [70 83 96]
 [37 44 51]]


In [49]:
x3 = np.array((1, 2, 3))
y3 = np.array((3, 4, 5))

In [52]:
print(np.column_stack((x3, y3)))
print(np.hstack((x3, y3)))
print(np.vstack((x3, y3)))

[[1 3]
 [2 4]
 [3 5]]
[1 2 3 3 4 5]
[[1 2 3]
 [3 4 5]]


EXERCISE 2  --- --- --- --- --- --- --- --- --- --- --- ---
Write a script that
- creates a matrix 5x5 from 5 numerical vectors;
- returns the diagonal of the matrix;
- transposes the matrix;
- multiplies the new matrix with the original matrix;
- extracts the last row of the resulting matrix;
- extracts the third column of the resulting matrix.

5. Lists and Dictionaries

In [62]:
from datetime import date
today = date.today()
d = {"name":"Pippo", "values":(20, 125, 40), "date":today}
print(d)
#THis is actually a dictionary

{'name': 'Pippo', 'values': (20, 125, 40), 'date': datetime.date(2023, 3, 29)}


In [66]:
d["date"]
myDate = d["date"]

In [72]:
print(d["date"])
print(d.values())

2023-03-29
dict_values(['Pippo', (20, 125, 40), datetime.date(2023, 3, 29)])


6. Factors

In [76]:
import pandas as pd
v = pd.Series(["John", "Sara", "Anthony", "Frank", "Sara", "Stephanie", "Anthony", "Anthony"])
vFactor = pd.Categorical(v)
print(vFactor)


['John', 'Sara', 'Anthony', 'Frank', 'Sara', 'Stephanie', 'Anthony', 'Anthony']
Categories (5, object): ['Anthony', 'Frank', 'John', 'Sara', 'Stephanie']
